#!/usr/bin/env bash

if [ -z "$ENNAME" ];then
    ENNAME=eth0
fi

set -o nounset -o errexit
export PATH=/usr/sbin:/usr/bin:$PATH
echo $(ip addr show $ENNAME | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
